### ISSUE TITLE
The repo is empty

### ISSUE THREAD

**Issue by mortenbekditlevsen** [MobilePayDev/MobilePay-PoS-v10-Client-Reference-Implementation#1]
The README suggests that this repo will contain a reference implementation of the PoS v10 client, but it does not.

**Comment by toughcare** [comment]
Hi Morten, the Repo was done as preparation for a Reference Implementation. However it has been decided to not provide a reference implementation for the PoS v10 client. I will update the README file to reflect this.
kind regards
Thomas Toftkjær
Chief Software Engineer
MobilePay Point-of-Sale
